#
# GNU GPLv3 License - see LICENSE.md at project root for terms.
# If for any reason this file has been separated from the license text,
# see LICENSE.md file in the git repo at https://github.com/Liam-Waaga/6502-emulator/blob/main/LICENSE.md
#


#!build/6502
# Make sure to run it from the project root, and make sure that 6502-emulator is built
# Replace the shebang with /usr/bin/6502-emulator or wherever

[system]
loglevel = info # Loglevel has 4 possible values, quiet, error, warn, and info. All but the first one can be defined here, and the first can be defined in command line
clock_speed = 1_000_000 # 1 Mhz, set to 0 to not emulate clock speed. Supports arbitrary '_''s in numbers

[ram]
address_begin = 0 #
address_end = 32768 # 2**15, exclusive, doesn't include address_end in the address space of a device, in bytes

[rom]
address_begin = 32768 # 32768 is only mapped to rom
address_end = 65536 # 2**16
path = "rom.bin"

